### ISSUE TITLE
Question about Windows support

### ISSUE THREAD

**Issue by BareBoneCode** [sperrichon/hori-mini-wired-gamepad-remote-play#1]
Is there a way to get this to work on Windows?

**Comment by p-sam** [comment]
The method used here is overriding OSX Library functions (specifically IOHID lib to interfaces with HID devices). It's unfortunately not possible to make this work on Windows since both the method to override functions and the librairies would be different. Try looking at https://github.com/nefarius/ViGEm and see if it can fit your needs.

**Comment by BareBoneCode** [comment]
Thank you
