### ISSUE TITLE
Cannot let it work

### ISSUE THREAD

**Issue by gianemi2** [sperrichon/hori-mini-wired-gamepad-remote-play#3]
Hi, when I try to follow the build guide. 
At this point 
./compile-lib.sh

Returns an error:
ld: can't open output file for writing: /Users/marcogiannini/Desktop/hori-mini-wired-gamepad-remote-play/build/../out/iohid_wrap.dylib, errno=2 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
EDIT: Resolved. I've to create the folder and the file before run compile-lib.sh.

Is possible to make this script also for Nacon Revolution Controller?

**Comment by p-sam** [comment]
Hi,

Your problem is just that the directory `/Users/marcogiannini/Desktop/hori-mini-wired-gamepad-remote-play/out` was not created creating an empty directory there will solve your issue, I updated the build script so it does anyway.

Also, if the Nacon Revolution Controller behaves mostly or exactly the same as a Dualshock 4 controller you could try editing the `SPOOF_VENDOR_ID` and `SPOOF_PRODUCT_ID` to match your controller values and see if it works.

**Comment by gianemi2** [comment]
Thank you so much @sperrichon 

Yes that was the problem. But also i've to create the empty file before run the compiler (you should add it to prerequisites in readme).

Where can I get the `SPOOF_VENDOR_ID` and `SPOOF_PRODUCT_ID`? The behaves is exactly the same as a Dualshock 4, in fact is a Sony Official controller.

**Comment by p-sam** [comment]
What do you mean "create the empty file" ? I only needed to create the directory earlier.

Plug your controller and go to `About This Mac` > `System Report`, find the `USB` section, and find your device in that section, the vendor id and product id should be listed here.

**Comment by gianemi2** [comment]
Thank you so much! It works perfectly with my Revolution Controller Pro changing the two line.

**Comment by p-sam** [comment]
No problem, I'll close the issue
